#pragma config(Sensor, S1,     sonar,          sensorSONAR)
#pragma config(Sensor, S2,     light,          sensorLightActive)
#pragma config(Motor,  motorA,          rightMotor,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          leftMotor,     tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//black is anything under 25
//blue is between 25 and 45
//white is over 45 
//Sonar distance for task 1 is 27


task main()
{
	while(sensorValue[sonar]>30){//Turn until an object is found
		motor[rightMotor]=25;
		motor[leftMotor]=-25;
	}
	wait1Msec(100);	
	while(SensorValue[light]<=45){
		motor[rightMotor]=50;
		motor[leftMotor]=50;
	}
	motor[leftMotor]=0;
	motor[rightMotor]=0;
} 
